-- MySQL Script generated by MySQL Workbench
-- Sun Mar 24 14:10:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema snapsort
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema snapsort
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snapsort` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `snapsort` ;

-- -----------------------------------------------------
-- Table `snapsort`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snapsort`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `role` ENUM('user', 'admin') NOT NULL,
  `subscribed` TINYINT(1) NULL DEFAULT '0',
  `verified` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone` (`phone` ASC) VISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE,
  INDEX `idx_phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `snapsort`.`auths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snapsort`.`auths` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `code` VARCHAR(8) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auths_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snapsort`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `snapsort`.`buckets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snapsort`.`buckets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `origin` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `origin` (`origin` ASC) VISIBLE,
  INDEX `idx_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_origin` (`origin` ASC) VISIBLE,
  CONSTRAINT `buckets_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snapsort`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `snapsort`.`folders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snapsort`.`folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `root` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_root` (`root` ASC) VISIBLE,
  CONSTRAINT `folders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snapsort`.`users` (`id`),
  CONSTRAINT `folders_ibfk_2`
    FOREIGN KEY (`root`)
    REFERENCES `snapsort`.`folders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `snapsort`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `snapsort`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `folder_id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url` (`url` ASC) VISIBLE,
  INDEX `idx_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_folder_id` (`folder_id` ASC) VISIBLE,
  INDEX `idx_url` (`url` ASC) VISIBLE,
  CONSTRAINT `files_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `snapsort`.`users` (`id`),
  CONSTRAINT `files_ibfk_2`
    FOREIGN KEY (`folder_id`)
    REFERENCES `snapsort`.`folders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
